### PR TITLE
[DEPLOY-100] Use the Internal Hadoop

### PR DESCRIPTION
**Pull request by merlintang**
## What changes were proposed in this pull request?

(Please fill in changes proposed in this fix)

## How was this patch tested?

(Please explain how this patch was tested. E.g. unit tests, integration tests, manual tests)
(If this patch involves UI changes, please attach a screenshot; otherwise, remove this)

### CODE REVIEW

**Comment by merlintang** [comment]
@dongjoon-hyun  @bikassaha  I would commit this to branch 2.6.0.10.

**Comment by merlintang** [comment]
https://github.com/hortonworks/build-manifests/blob/master/HDP/2.6/2.6.0.10/manifests/2.6.0.10-1.txt should we use this hive2 version?

**Comment by dongjoon-hyun** [comment]
Why don't use the version installed in your test cluster?

**Comment by merlintang** [comment]
The test cluster is dead. we can the same version number as the Hadoop.

**Pull request merged**
