### PR TITLE
[SPARK-LLAP-174] Add LlapQuery class to be able to run full queries from HS2/LLAP

### PR DESCRIPTION
**Pull request by jdere**
## What changes were proposed in this pull request?

- Add LlapQuery class to be able to run full queries from HS2/LLAP
- Add currentdatabase option to LlapRelation
- Use handleId so LlapBaseInputFormat resources can be closed

### CODE REVIEW

**Comment by dongjoon-hyun** [comment]
Since this is for Spark 2.2, @merlintang will test and merge this to `branch-2.2` and `master`.

**Comment by merlintang** [comment]
sure, let me create a cluster and test it later.

**Comment by jdere** [comment]
This requires HIVE-17455, which is available in Hive version 2.1.0.2.6.3.0-79, though I do not see this in the repository listed in build.sbt.

**Comment by dongjoon-hyun** [comment]
@jdere . You can use `repourl` option. RE uses that.

**Comment by jdere** [comment]
I've committed the changes to branch-2.2

**Pull request closed without merging**
