### PR TITLE
[SPARK-LLAP-188] Use Apache Spark 2.3

### LINKED ISSUE #188: Use Apache Spark 2.3

### PR DESCRIPTION
**Pull request by dongjoon-hyun**
## What changes were proposed in this pull request?

Recently, Apache Spark 2.3 is released offcially. This PR updates the dependency to Apache Spark 2.3.

## How was this patch tested?

Pass the Travis CI build test.

This closes #188 .

### CODE REVIEW

**Comment by dongjoon-hyun** [comment]
Could you review this, @jdere and @weiqingy ?

**Comment by weiqingy** [comment]
+1, LGTM.

**Comment by weiqingy** [comment]
I should have copied the description when merging the PR. :(

**Comment by dongjoon-hyun** [comment]
Thank you so much, @weiqingy . It's okay~

**Pull request merged**
