### PR TITLE
Push down count(*) query to Hive when requiredColumns is an empty list.

### PR DESCRIPTION
**Pull request by jdere**
This improves performance of count(*) queries since we were previously selecting all columns of the table.

## What changes were proposed in this pull request?

(Please fill in changes proposed in this fix)

## How was this patch tested?

(Please explain how this patch was tested. E.g. unit tests, integration tests, manual tests)
(If this patch involves UI changes, please attach a screenshot; otherwise, remove this)

### CODE REVIEW

**Comment by dongjoon-hyun** [comment]
Wait a minute please, @jdere and @merlintang .

Strangely, it seems I missed to add one answer file in the last commit after testing.
- src/test/resources/answer/select_1_t_no.err_answer

I'm testing again the patch.

**Comment by dongjoon-hyun** [comment]
It's fixed now, @jdere and @merlintang .
@merlintang . You can test and merge this.

**Comment by merlintang** [comment]
@dongjoon-hyun  do you test this patch on the branch-1.6? because the branch-1.6 does not have the spark-ranger-secure-test.py, do you update the security test on your own branch? if it is possible, can you submit this patch to branch 1.6, then I can use it for testing branch 1.6. Thanks.

**Comment by dongjoon-hyun** [comment]
Sorry for making you confused. That's the result for https://github.com/hortonworks-spark/spark-llap/commit/dcb75f46471657bbfde9a348cb3af8092e638ec8 . 

I didn't review and didn't test this.

**Comment by merlintang** [comment]
thanks for letting me know.

**Comment by merlintang** [comment]
The test result base on spark-ranger-secure-test.py

test_00_show
test_50_select
test_60_select_count
test_90_mask
test_A0_filter

```
[root@ctr-e133-1493418528701-160107-01-000009 python]#  ./spark-ranger-secure-test.py TableTestSuite
.....
----------------------------------------------------------------------
Ran 5 tests in 553.255s

OK

**Comment by merlintang** [comment]
if the scala style is not a big issue, we can merge it now.

**Comment by dongjoon-hyun** [comment]
For Jason's commit, we had better fix the scalastyle by ourselves. Please merge this and create another PR for scala style fix.

**Comment by merlintang** [comment]
ok, let us merge this, and I can file a PR for the scala style.

**Comment by dongjoon-hyun** [comment]
Thanks! For your scala style fix, you can merge when Travis CI passed. :)

**Pull request merged**
