### PR TITLE
[SPARK-LLAP-125] Reduce the number of included artifacts in the assembly jar

### PR DESCRIPTION
**Pull request by merlintang**
## What changes were proposed in this pull request?

1.  change some artifact from compile to provided
2.  exclude the hadoop common from hive
3.  remove the force for the spark
4.  exclude: commons-beanutils etc

## How was this patch tested?
I manually test the complied jar in the set up cluster.

### CODE REVIEW

**Comment by merlintang** [comment]
@bikassaha @dongjoon-hyun  please review it. thanks

**Comment by dongjoon-hyun** [comment]
Could you review the template statement from PR description?
- (Please fill in changes proposed in this fix)
- (Please explain how this patch was tested. E.g. unit tests, integration tests, manual tests)
- (If this patch involves UI changes, please attach a screenshot; otherwise, remove this)

**Comment by dongjoon-hyun** [comment]
@jdere . Is the Hive snapshot is published? Is there any way to build successfully in a public world?

**Comment by dongjoon-hyun** [comment]
Ping, @merlintang and @jdere .

**Comment by dongjoon-hyun** [comment]
Also, please update the title. Let's not to use the internal jira issue number here.

**Comment by jdere** [comment]
@dongjoon-hyun, you can use -Drepourl and -Dhive.version to point the build to use the Maven repo with the daily builds, and point it to a recent daily build.

**Comment by dongjoon-hyun** [comment]
Yep. QE works like that. This is for tracking our work record about publishing .

**Comment by merlintang** [comment]
Thanks all, I have fixed these comments.

**Comment by dongjoon-hyun** [comment]
Ur, what do you mean, @merlintang ?
For 2, 3, 4, I didn't find any answer from you.

**Comment by merlintang** [comment]
@dongjoon-hyun  

Could you test this with YARN cluster mode in the kerberized cluster, too?

      Yes, I have test this jar in the Yarn cluster model in the kerberzied cluster. 

For the other two questions, let me check and send you feedback soon. Sorry, I did not see your other questions.

**Comment by merlintang** [comment]
(2)
the size of jar before is 
105122013 May 19 22:54 target/scala-2.11/spark-llap-assembly-1.1.1-2.1.jar
later is reduced to
95823291 May 19 22:59 target/scala-2.11/spark-llap-assembly-1.1.1-2.1.jar

(3) for the dependence tree
I generated the sbt depend tree, and find both of them have many differences.

**Comment by dongjoon-hyun** [comment]
What do you mean (3)? I think the purpose of this PR is to verify that there is no difference before and after. 

@bikassaha . Given the current result of (2) and (3), I'd like suggest to stop this PR and the issue for now.

**Comment by merlintang** [comment]
@dongjoon-hyun  the dependence tree should be changed. right? because we already change the dependence.

**Comment by merlintang** [comment]
I will file new patch based on branch 2.1 and test it over a spark2-llap cluster, I will close this PR, and we can track this from this PR.  https://github.com/hortonworks-spark/spark-llap/pull/142

**Pull request closed without merging**
